apiVersion: batch/v1
kind: CronJob
metadata:
  name: webapp-mysqlbackup
spec:
  schedule: "3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: webapp-mysqlbackup
            image: ghcr.io/drakeapps/mysqlbackup-gdrive
            imagePullPolicy: Always
            env:
              - name: MYSQL_USER
                value: root
              - name: MYSQL_PASS
                valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password
              - name: MYSQL_HOST
                value: webapp-mysql
              - name: MYSQL_DB
                value: webapp
              - name: RCLONE_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: rclone-token
                    key: token
              - name: DEST_DIR
                value: /backups/k8s/db-backups/webapp/
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: mysecretname


